flashkernel: openwrt/bin/s3c24xx/openwrt-s3c24xx-2.6-uImage
	dfu-util -a kernel -R -D openwrt/bin/s3c24xx/openwrt-s3c24xx-2.6-uImage

flashrootfs:
	dfu-util -a rootfs -R -D openwrt/bin/s3c24xx/openwrt-s3c24xx-root.jffs2-128k

